//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KProj.Models.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public string CommentText { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<System.DateTime> datePost { get; set; }
        public Nullable<int> Course_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
    
        public virtual Cour Cour { get; set; }
        public virtual UserData UserData { get; set; }
    }
}
